version: '2'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003:2003"

  config:
    image: 'config:latest'
    build:
      context: ./config
      dockerfile: Dockerfile
    container_name: config
    environment:
      - EUREKA_URL=http://discovery:8761/eureka
      - APP_CONFIG_REPO=https://github.com/VitaliiLapov96/application-config-repo.git
    ports:
      - "8765:8765"

  discovery:
    image: 'discovery:latest'
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery
    environment:
      - CONFIG_SERVER_URL=configserver:http://localhost:8765
    ports:
      - "8761:8761"

  apigateway:
    image: 'apigateway:latest'
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: apigateway
    environment:
      - EUREKA_URL=http://discovery:8761/eureka
      - CONFIG_SERVER_URL=configserver:http://localhost:8765
    ports:
      - "8764:8764"
    depends_on:
      - discovery

  event-app:
    image: 'event-core:latest'
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: event-core
    ports:
      - "8080:8080"
    depends_on:
      - db
      - discovery
      - zipkin
      - graphite
    environment:
      - MY_POSTGRES_URL=jdbc:postgresql://db:5432/events
      - USERNAME=postgres
      - PASSWORD=postgres
      - EUREKA_URL=http://discovery:8761/eureka
      - CONFIG_SERVER_URL=configserver:http://localhost:8765

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events

#  discovery:
#    build: ../event-app/discovery/target/docker
#    ports:
#      - "8761:8761"
#
#  apigateway:
#    build: ../event-app/apigateway/target/docker
#    ports:
#      - "8764:8764"
#    links:
#      - discovery