version: '2.1'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003:2003"

  config:
    image: 'config:latest'
    build:
      context: ./config
      dockerfile: Dockerfile
    container_name: config
    environment:
      - APP_CONFIG_REPO=https://github.com/VitaliiLapov96/application-config-repo.git
    ports:
      - "8888:8888"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  discovery:
    image: 'discovery:latest'
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery
    environment:
      - CONFIG_SERVER_URL=optional:configserver:http://config:8888
    ports:
      - "8761:8761"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery:8761/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      config:
        condition: service_healthy

  api-gateway:
    image: 'apigateway:latest'
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: apigateway
    environment:
      - CONFIG_SERVER_URL=optional:configserver:http://config:8888
      - EUREKA_URL=http://discovery:8761/eureka
    ports:
      - "8764:8764"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-gateway:8764/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      discovery:
        condition: service_healthy

  event-app:
    image: 'event-core:latest'
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: event-app
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER_URL=optional:configserver:http://config:8888
      - EUREKA_URL=http://discovery:8761/eureka
      - MY_POSTGRES_URL=jdbc:postgresql://db:5432/events
      - USERNAME=root
      - PASSWORD=Root123
      - ZIPKIN_SERVER_URL=http://zipkin:9411
    restart: on-failure
    depends_on:
      api-gateway:
        condition: service_healthy

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Root123
      - POSTGRES_DB=events
    restart: on-failure

  data-generator:
    image: 'data-generator:latest'
    build:
      context: ./data-generator
      dockerfile: Dockerfile
    container_name: data-generator
    ports:
      - "8081:8081"
    environment:
      - CONFIG_SERVER_URL=optional:configserver:http://config:8888
      - EUREKA_URL=http://discovery:8761/eureka
      - ZIPKIN_SERVER_URL=http://zipkin:9411
    restart: on-failure
    depends_on:
      api-gateway:
        condition: service_healthy