version: '2'

services:
  app:
    image: 'event-core:latest'
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: event-core
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MY_POSTGRES_URL=jdbc:postgresql://db:5432/events
      - USERNAME=postgres
      - PASSWORD=postgres

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events