#App name/Config server configuration
spring:
  application:
    name: api-gateway
  config:
    import: ${CONFIG_SERVER_URL}

#Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'