#App name/Postgres configuration
spring:
  cloud:
    import: configserver:http://localhost:8888
  application:
    name: event-app

#Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'