#App name configuration
spring:
  application:
    name: discovery

  cloud:
    config:
      import: ${CONFIG_SERVER_URL}

#Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
