#Spring configuration
server:
  port: 8081
  servlet:
    context-path: /data-generator

#App name configuration
spring:
  application:
    name: data-generator

##Eureka configuration
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URL}